---
- name: OPENLDAP | Add user to group | Set uid for user
  ansible.builtin.set_fact:
    user_id: "{%if user.uid is defined%}{{ user.uid }}{%else%}{{ (user.firstName[0] + '.' + user.lastName) | lower }}{%endif%}"

- name: OPENLDAP | Add user to group | Add user {{ user_id }} to groups
  community.general.ldap_attrs:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "cn={{ item }},ou=groups,{{ ldap_root }}"
    attributes:  
      memberuid: "{{ user_id }}"
    state: present
  with_items: "{{ user.groups | default ([]) }}"


- name: OPENLDAP | Add user to group | Create authgroup for user {{ user_id }}
  community.general.ldap_entry:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "cn={{ item }},ou=authgroups,{{ ldap_root }}"
    objectClass:
      - groupOfNames
    attributes:  
      member: "uid={{ user_id }},ou=users,{{ ldap_root }}"
      cn: "{{ item }}"
    state: present
  with_items: "{{ user.authgroups | default ([]) }}"

- name: OPENLDAP | Add user to group | Add user {{ user_id }} to authgroup
  community.general.ldap_attrs:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "cn={{ item }},ou=authgroups,{{ ldap_root }}"
    attributes:  
      member: "uid={{ user_id }},ou=users,{{ ldap_root }}"
    state: present
  with_items: "{{ user.authgroups | default ([]) }}"
