---
- name: OPENLDAP | Install | Ensure needed packages
  ansible.builtin.apt:
    name: "{{ ldap_server_packages }}"
    update_cache: yes

- name: OPENLDAP | Install | Ensure pip requirements
  ansible.builtin.pip:
    name: "{{ ldap_pip_requirements }}"

- name: OPENLDAP | Install | Ensure needed directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: 1001
  with_items:
    - "{{ ldap_data }}"
    - "{{ ldap_tls_cert_host_path }}"

- name: OPENLDAP | Install | Start openldap container
  community.docker.docker_compose:
    project_name: openldap
    definition:
      version: '3'
      services:
        openldap:
          image: "{{ ldap_image }}:{{ ldap_version }}"
          container_name: openldap
          restart: always
          ports:
            - '{{ ldap_interface }}:{{ ldap_port }}:1389'
            - '{{ ldap_interface }}:{{ ldaps_port }}:1636'
          environment:
            - LDAP_ROOT={{ ldap_root }}
            - LDAP_ADMIN_USERNAME={{ ldap_admin_username }}
            - LDAP_ADMIN_PASSWORD={{ ldap_admin_password }}
            - LDAP_CONFIG_ADMIN_ENABLED=yes
            - LDAP_CONFIG_ADMIN_USERNAME={{ ldap_admin_username }}
            - LDAP_CONFIG_ADMIN_PASSWORD={{ ldap_admin_password }}
            - LDAP_SKIP_DEFAULT_TREE=yes
            - LDAP_ALLOW_ANON_BINDING=no
            - LDAP_ENABLE_TLS={{ ldap_enable_tls }}
            - LDAP_TLS_CERT_FILE={{ ldap_tls_cert_path }}/{{ ldap_tls_cert_file_name }}
            - LDAP_TLS_KEY_FILE={{ ldap_tls_cert_path }}/{{ ldap_tls_key_file_name }}
            - LDAP_TLS_CA_FILE={{ ldap_tls_cert_path }}/{{ ldap_tls_ca_file_name }}
          volumes:
            - '{{ ldap_data }}:/bitnami/openldap'
            - '{{ ldap_tls_cert_host_path }}:{{ ldap_tls_cert_path }}:ro'

- name: OPENLDAP | Install | Create organisation {{ ldap_root }}
  community.general.ldap_entry:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "{{ ldap_root }}"
    objectClass:
      - dcObject
      - organization
    attributes:
      dc: "{{ ldap_root_dc }}"
      o: "{{ ldap_organisation }}"
  register: connect_result
  retries: 5
  delay: 3
  until: connect_result is not failed

- name: OPENLDAP | Install | Create openssh-lpk in cn=config
  community.general.ldap_entry:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},cn=config"
    bind_pw: "{{ ldap_admin_password }}"
    dn: cn=openssh-lpk,cn=schema,cn=config
    objectClass: olcSchemaConfig
    attributes:
      olcAttributeTypes: >-
        {0}( 1.3.6.1.4.1.24552.500.1.1.1.13 NAME 'sshPublicKey'
        DESC 'MANDATORY: OpenSSH Public key'
        EQUALITY octetStringMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.40 )
      olcObjectClasses: >-
        {0}( 1.3.6.1.4.1.24552.500.1.1.2.0 NAME 'ldapPublicKey'
        DESC 'MANDATORY: OpenSSH LPK objectclass'
        SUP top AUXILIARY MAY ( sshPublicKey $ uid ) )
  register: config_openssh_lpk
  failed_when:
    - config_openssh_lpk.details is defined
    - '{{ "Duplicate" not in config_openssh_lpk.details }}'
    - not config_openssh_lpk.changed

- name: OPENLDAP | Install | Create readonly user
  community.general.ldap_entry:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "cn={{ ldap_readonly_username }},{{ ldap_root }}"
    objectClass:
      - simpleSecurityObject
      - organizationalRole
    attributes:
      userPassword: "{{ ldap_readonly_passwordHash }}"
      cn: "{{ ldap_readonly_username }}"

- name: OPENLDAP | Install | Change password for readonly user
  community.general.ldap_passwd:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "cn={{ ldap_readonly_username }},{{ ldap_root }}"
    passwd: "{{ ldap_readonly_password }}"
  when: ldap_readonly_password is defined

- name: OPENLDAP | Install | Create alcAccess
  community.general.ldap_attrs:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},cn=config"
    bind_pw: "{{ ldap_admin_password }}"
    dn: olcDatabase={2}mdb,cn=config
    attributes:
      olcAccess: "{{ ldap_mdb_olcAccess }}"
    state: "exact"

- name: OPENLDAP | Install | Add modules
  block:
    - name: OPENLDAP | Install | Create cn=module{0},cn=config
      community.general.ldap_entry:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},cn=config"
        bind_pw: "{{ ldap_admin_password }}"
        dn: cn=module{0},cn=config
        objectClass:
          - olcModuleList
        attributes:
          cn: module{0}
          olcModulePath: /opt/bitnami/openldap/lib/openldap

    - name: OPENLDAP | Install | Add olcModuleLoad to cn=module{0},cn=config
      community.general.ldap_attrs:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},cn=config"
        bind_pw: "{{ ldap_admin_password }}"
        dn: cn=module{0},cn=config
        attributes:
          olcModuleLoad: "{{ ldap_olcmoduleload }}"

    - name: OPENLDAP | Install | Create olcOverlay=memberof,olcDatabase={2}mdb,cn=config
      community.general.ldap_entry:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},cn=config"
        bind_pw: "{{ ldap_admin_password }}"
        dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
        objectClass:
          - olcOverlayConfig
          - olcMemberOf
        attributes:
          olcOverlay: memberof
          olcMemberOfRefint: "TRUE"

    - name: OPENLDAP | Install | Ensure ou=pwPolicies
      community.general.ldap_entry:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
        bind_pw: "{{ ldap_admin_password }}"
        dn: "ou=pwPolicies,{{ ldap_root }}"
        objectClass:
          - organizationalUnit

    - name: OPENLDAP | Install | Create ppolices
      community.general.ldap_entry:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
        bind_pw: "{{ ldap_admin_password }}"
        dn: "cn={{ item.name }},ou=pwPolicies,{{ ldap_root }}"
        objectClass:
          - applicationProcess
          - pwdPolicy
        attributes:
          cn: "{{ item.name }}"
          pwdAttribute: 2.5.4.35
      with_items: "{{ ldap_ppolicies }}"

    - name: OPENLDAP | Install | Change ppolicies
      community.general.ldap_attrs:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
        bind_pw: "{{ ldap_admin_password }}"
        dn: "cn={{ item.name }},ou=pwPolicies,{{ ldap_root }}"
        attributes: "{{ item.policies }}"
        state: exact
      with_items: "{{ ldap_ppolicies }}"

    - name: OPENLDAP | Install | Create olcOverlay=ppolicy,olcDatabase={2}mdb,cn=config
      community.general.ldap_entry:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},cn=config"
        bind_pw: "{{ ldap_admin_password }}"
        dn: olcOverlay=ppolicy,olcDatabase={2}mdb,cn=config
        objectClass:
          - olcOverlayConfig
          - olcPPolicyConfig
        attributes:
          olcOverlay: ppolicy
          olcPPolicyDefault: "cn=default,ou=pwPolicies,{{ ldap_root }}"
          olcPPolicyHashCleartext: "FALSE"
          olcPPolicyUseLockout: "FALSE"
          olcPPolicyForwardUpdates: "FALSE"

    - name: OPENLDAP | Install | Add pwdPolicySubentry to readonly user
      community.general.ldap_attrs:
        server_uri: "ldap://localhost:{{ ldap_port }}"
        bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
        bind_pw: "{{ ldap_admin_password }}"
        dn: "cn={{ ldap_readonly_username }},{{ ldap_root }}"
        attributes:
          pwdPolicySubentry: "cn=reader,ou=pwPolicies,{{ ldap_root }}"

  when: ldap_add_modules
