---
- name: OPENLDAP | Install
  import_tasks: install_openldap.yml
  tags:
    - install_server
    - server
    - never

- name: OPENLDAP | Add group
  include_tasks:
    file: add_group.yml
    apply:
      tags:
        - add_group
        - server
        - never
  tags:
    - add_group
    - server
    - never
  with_items: "{{ ldap_groups_list }}"
  loop_control:
    loop_var: group

- name: OPENLDAP | Add user
  include_tasks:
    file: add_user.yml
    apply:
      tags:
        - add_user
        - server
        - never
  tags:
    - add_user
    - change_users_attributes
    - change_password
    - server
    - never
  with_items: "{{ ldap_users_list }}"
  loop_control:
    loop_var: user

- name: OPENLDAP | Add user to group
  include_tasks:
    file: add_user_to_group.yml
    apply:
      tags:
        - add_user_to_group
        - server
        - never
  tags:
    - add_user_to_group
    - server
    - never
  with_items: "{{ ldap_users_list }}"
  loop_control:
    loop_var: user

- name: OPENLDAP | Show users
  import_tasks: show_users.yml
  tags:
    - show_users
    - never

- name: OPENLDAP | Install client
  import_tasks: install_client.yml
  tags:
    - install_client
    - client

- name: unblock user
  community.general.ldap_attrs:
    server_uri: "ldap://localhost:{{ ldap_port }}"
    bind_dn: "cn={{ ldap_admin_username }},{{ ldap_root }}"
    bind_pw: "{{ ldap_admin_password }}"
    dn: "uid={{ item }},ou=users,{{ ldap_root }}"
    attributes:
      pwdAccountLockedTime: 000001010000Z
    state: absent
  with_items: "{{ ldap_unblock_users_list }}"
  tags: unblock
