---
- name: OPENLDAP | Install
  import_tasks: install_openldap.yml
  tags:
    - install_server
    - server
    - never

- name: OPENLDAP | Add group
  include_tasks:
    file: add_group.yml
    apply:
      tags:
        - add_group
        - server
        - never
  tags:
    - add_group
    - server
    - never
  with_items: "{{ ldap_groups_list }}"
  loop_control:
    loop_var: group

- name: OPENLDAP | Add user
  include_tasks:
    file: add_user.yml
    apply:
      tags:
        - add_user
        - server
        - never
  tags:
    - add_user
    - server
    - never
  with_items: "{{ ldap_users_list }}"
  loop_control:
    loop_var: user

- name: OPENLDAP | Add user to group
  include_tasks:
    file: add_user_to_group.yml
    apply:
      tags:
        - add_user_to_group
        - server
        - never
  tags:
    - add_user_to_group
    - server
    - never
  with_items: "{{ ldap_users_list }}"
  loop_control:
    loop_var: user

- name: OPENLDAP | Change users` attributes
  include_tasks:
    file: change_users_attributes.yml
    apply:
      tags:
        - change_users_attributes
        - never
  tags:
    - change_users_attributes
    - never
  with_items: "{{ ldap_users_list }}"
  loop_control:
    loop_var: changing_user

- name: OPENLDAP | Show users
  import_tasks: show_users.yml
  tags:
    - show_users
    - never

- name: OPENLDAP | Install client
  import_tasks: install_client.yml
  tags:
    - install_client
    - client
